### ISSUE TITLE
add the possibility for the user to customize the theme colors

### ISSUE THREAD

**Issue by datsfilipe** [datsfilipe/smooth-theme#13]

**Comment by datsfilipe** [comment]
this is already possible, user can check the [theme colors](https://github.com/datsfilipe/smooth-theme/blob/main/src/scss/abstracts/_theme-colors.scss), to get what theme colors he can overwrite and add them to the theme, e.g.:

```css
:root {
  /* theme version */
  --theme-version-2-3-0: 2.3.0;
  --background-primary: #ffffff;
}
```

this would work.
